grupyto-blog/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView

from zinnia.sitemaps import TagSitemap
from zinnia.sitemaps import EntrySitemap
from zinnia.sitemaps import CategorySitemap
from zinnia.sitemaps import AuthorSitemap

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()


handler404 = 'django.views.defaults.page_not_found'
handler403 = 'django.views.defaults.permission_denied'

urlpatterns = patterns('',
    url(r'^guard/doc/', include('django.contrib.admindocs.urls')),
    url(r'^guard/', include(admin.site.urls)),
    url(r'^$', RedirectView.as_view(url='/blog/')),
    url(r'^blog/', include('zinnia.urls')),
    url(r'^blog/comments/', include('django.contrib.comments.urls')),
    url(r'^', include('zinnia.urls.capabilities')),
    url(r'^blog/search/', include('zinnia.urls.search')),
    url(r'^blog/sitemap/', include('zinnia.urls.sitemap')),
    url(r'^blog/trackback/', include('zinnia.urls.trackback')),
    url(r'^blog/tags/', include('zinnia.urls.tags')),
    url(r'^blog/feeds/', include('zinnia.urls.feeds')),
    url(r'^blog/random/', include('zinnia.urls.random')),
    url(r'^blog/authors/', include('zinnia.urls.authors')),
    url(r'^blog/categories/', include('zinnia.urls.categories')),
    url(r'^blog/comments/', include('zinnia.urls.comments')),
    url(r'^blog/', include('zinnia.urls.entries')),
    url(r'^blog/', include('zinnia.urls.archives')),
    url(r'^blog/', include('zinnia.urls.shortlink')),
    url(r'^blog/', include('zinnia.urls.quick_entry')),
    url(r'^blog/xmlrpc/$', 'django_xmlrpc.views.handle_xmlrpc'),
)

#urlpatterns += patterns('',
#                       url(r'^velho/$',
#                           TemplateView.as_view(template_name='pages/home.html'),
#                           name="home"),
#                       url(r'^velho_about/$',
#                           TemplateView.as_view(template_name='pages/about.html'),
#                           name="about"),
#
#                       # Uncomment the next line to enable the admin:
#                       #url(r'^admin/', include(admin.site.urls)),
#
#                       # User management
#                       url(r'^users/', include("users.urls", namespace="users")),
#                       url(r'^accounts/', include('allauth.urls')),
#
#                       # Uncomment the next line to enable avatars
#                       url(r'^avatar/', include('avatar.urls')),
#
#                       # Your stuff: custom urls go here
#
#)

urlpatterns += patterns('',) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


sitemaps = {
    'tags': TagSitemap,
    'blog': EntrySitemap,
    'authors': AuthorSitemap,
    'categories': CategorySitemap
}

urlpatterns += patterns(
    'django.contrib.sitemaps.views',
    url(r'^sitemap.xml$', 'index',
        {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', 'sitemap',
        {'sitemaps': sitemaps}),
)

urlpatterns += patterns(
    '',
    url(r'^403/$', 'django.views.defaults.permission_denied'),
    url(r'^404/$', 'django.views.defaults.page_not_found'),
)

grupyto-blog/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from users import views

urlpatterns = patterns('',
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w\-_]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
)

grupyto-blog/users/models.py
# -*- coding: utf-8 -*-
# Import the AbstractUser model
from django.contrib.auth.models import AbstractUser

# Import the basic Django ORM models library
from django.db import models

from django.utils.translation import ugettext_lazy as _


# Subclass AbstractUser
class User(AbstractUser):

    def __unicode__(self):
        return self.username

grupyto-blog/users/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import User


class UserForm(forms.ModelForm):

    class Meta:
        # Set this form to use the User model.
        model = User

        # Constrain the UserForm to just these fields.
        fields = ("first_name", "last_name")

grupyto-blog/users/views.py
# -*- coding: utf-8 -*-
# Import the reverse lookup function
from django.core.urlresolvers import reverse

# view imports
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView
from django.views.generic import ListView

# Only authenticated users can access views using this.
from braces.views import LoginRequiredMixin

# Import the form from users/forms.py
from .forms import UserForm

# Import the customized User model
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
            kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    form_class = UserForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                    kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

grupyto-blog/templates/avatar/add.html
{% extends "avatar/base.html" %}
{% load i18n avatar_tags %}
{% load url from future %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h2>{% trans "Your current avatar: " %}</h2>
        {% avatar user %}
        {% if not avatars %}
            <p>{% trans "You haven't uploaded an avatar yet. Please upload one now." %}</p>
        {% endif %}
        <form enctype="multipart/form-data" method="POST" action="{% url 'avatar_add' %}">
            {{ upload_avatar_form.as_p }}
            <p>{% csrf_token %}<input type="submit" value="{% trans "Upload New Image" %}" /></p>
        </form>
    </div>
  </div>
</div>
{% endblock %}

grupyto-blog/templates/avatar/avatar_tag.html
<img src="{{ url }}" width="{{ size }}" height="{{ size }}" class="img-thumbnail">

grupyto-blog/templates/avatar/base.html
{% extends "base.html" %}

{% block title %}django-avatar{% endblock %}
{% block content %}{% endblock %}

grupyto-blog/templates/avatar/change.html
{% extends "avatar/base.html" %}
{% load i18n avatar_tags %}
{% load url from future %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
        <h2>{% trans "Your current avatar: " %}</h2>
        {% avatar user %}
        {% if not avatars %}
            <p>{% trans "You haven't uploaded an avatar yet. Please upload one now." %}</p>
        {% else %}
            <form method="POST" action="{% url 'avatar_change' %}">
                <ul>
                    {{ primary_avatar_form.as_ul }}
                </ul>
                <p>{% csrf_token %}<input type="submit" value="{% trans "Choose new Default" %}" /></p>
            </form>
        {% endif %}
        <form enctype="multipart/form-data" method="POST" action="{% url 'avatar_add' %}">
            {{ upload_avatar_form.as_p }}
            <p>{% csrf_token %}<input type="submit" value="{% trans "Upload New Image" %}" /></p>
        </form>
    </div>
  </div>
</div>
{% endblock %}

grupyto-blog/templates/avatar/confirm_delete.html
{% extends "avatar/base.html" %}
{% load i18n %}
{% load url from future %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
    <h2>{% trans "Please select the avatars that you would like to delete." %}</h2>
    {% if not avatars %}
        {% url 'avatar_change' as avatar_change_url %}
        <p>{% blocktrans %}You have no avatars to delete. Please <a href="{{ avatar_change_url }}">upload one</a> now.{% endblocktrans %}</p>
    {% else %}
        <form method="POST" action="{% url 'avatar_delete' %}">
            <ul>
                {{ delete_avatar_form.as_ul }}
            </ul>
            <p>{% csrf_token %}<input type="submit" value="{% trans "Delete These" %}" /></p>
        </form>
    {% endif %}
    </div>
  </div>
</div>
{% endblock %}

grupyto-blog/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" ng-app>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}grupyto-blog{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css">

    <!-- Your stuff: Third-party css libraries go here -->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

    {% block angular %}
      <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js"></script>
    {% endblock %}

  </head>

  <body>

    <div class="header navbar">
      <div class="container">
        <a class="navbar-brand" href="/">grupyto-blog</a>
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'about' %}">About</a></li>

          {% if request.user.is_authenticated %}
            <li><a href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a></li>
            <li><a href="{% url 'account_logout' %}">{% trans "Logout" %}</a></li>
          {% else %}
            <li><a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
            <li><a href="{% url 'account_login' %}">{% trans "Log In" %}</a></li>
          {% endif %}
        </ul>
      </div>
    </div>

    <div class="container">
        
      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->
    
    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  </body>
</html>
 

grupyto-blog/templates/comments/zinnia/entry/form.html
{% load comments i18n %}
<form action="{% comment_form_target %}" method="post" id="comment-form">
  <div>{% csrf_token %}</div>
  <fieldset>
    <legend>{% trans "Post your comment" %}</legend>
    <input type="hidden" name="next" value="{% url 'zinnia_comment_success' %}"/>
    {% for field in form %}
    {% if field.is_hidden %}{{ field }}{% else %}
    {% if user.email and field.name in "namemailurl" %}{% else %}
    <div{% if field.errors %} class="error"{% endif %}{% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}>
      {{ field.label_tag }}
      {% if field.errors %}{{ field.errors }}{% endif %}
      {{ field }}
    </div>
    {% endif %}
    {% endif %}
    {% endfor %}
    {% if user.is_authenticated %}
    <p class="auth">
      {% trans "Comment as" %} <strong>{% firstof user.get_full_name user.username %}</strong>. <a href="{% url 'admin:logout' %}">{% trans "Log out" %}</a>.
    </p>
    {% endif %}
    <p class="submit">
      <input type="submit" name="submit" class="submit-post" value="{% trans "Post" %}" />
      <input type="submit" name="preview" class="submit-preview" value="{% trans "Preview" %}" />
    </p>
  </fieldset>
</form>

grupyto-blog/templates/comments/zinnia/entry/posted.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block title %}{% trans "Thanks for your comment" %}{% endblock title %}

{% block body-class %}comment-posted{% endblock body-class %}

{% block content %}
<h2>{% trans "Thanks for your comment" %}</h2>

<p>{% trans "Your comment needs to be approved before getting displayed." %}</p>

<ul>
  {% if comment %}
  <li>
    {% with entry=comment.content_object %}
    <a href="{{ entry.get_absolute_url }}"
       title="{{ entry.title }}">
      {% blocktrans with title=entry.title %}Back to {{ title }}{% endblocktrans %}
    </a>
    {% endwith %}
  </li>
  {% endif %}
  <li>
    <a href="{% url 'zinnia_entry_archive_index' %}"
       title="{% trans "Return to entry list" %}">
      {% trans "Return to entry list" %}
    </a>
  </li>
</ul>
{% endblock content %}

grupyto-blog/templates/comments/zinnia_entry_preview.html
{% extends "zinnia/base.html" %}
{% load i18n zinnia_tags comments %}

{% block title %}{% trans "Comment preview" %}{% endblock title %}

{% block body-class %}comment-preview{% endblock body-class %}

{% block content %}
  {% if form.errors %}
  <h2>{% blocktrans count errors=form.errors|length %}Please correct following error.{% plural %}Please correct following errors.{% endblocktrans %}</h2>
  {% else %}
  <h2>{% trans "Preview of the comment" %}</h2>
  <ol id="comment-list">
    {% with comment=form.get_comment_object %}
    <li id="comment-preview" class="comment vcard box1">
      <img src="{% get_gravatar comment.email 60 "G" %}"
           class="gravatar photo" alt="{{ comment.name }}" />
      <p class="comment-info">
	{% if comment.url %}
	<a href="{{ comment.url }}" rel="external nofollow"
           class="fn url">{{ comment.name }}</a>
	{% else %}
	{{ comment.name }}
	{% endif %}
	{% trans "on" %}
        <abbr class="comment-published" title="{{ comment.submit_date|date:"c" }}">
          {{ comment.submit_date|date:"SHORT_DATETIME_FORMAT" }}
        </abbr>
      </p>
      {{ comment.comment|linebreaks }}
    </li>
    {% endwith %}
  </ol>
  {% endif %}
  {% include "comments/zinnia/entry/form.html" %}
{% endblock content %}

grupyto-blog/templates/feeds/comment_description.html
{{ obj.comment }}

grupyto-blog/templates/feeds/comment_title.html
{% load i18n %}
{{ obj.name }} {% trans "on" %} {{ obj.submit_date|date:"DATETIME_FORMAT" }}

grupyto-blog/templates/feeds/discussion_description.html
{{ obj.comment }}

grupyto-blog/templates/feeds/discussion_title.html
{% load i18n %}
{{ obj.name }} {% trans "on" %} {{ obj.submit_date|date:"DATETIME_FORMAT" }}

grupyto-blog/templates/feeds/entry_description.html
{{ obj.html_content|safe }}

grupyto-blog/templates/feeds/entry_title.html
{{ obj.title|safe }}

grupyto-blog/templates/feeds/pingback_description.html
{{ obj.comment }}

grupyto-blog/templates/feeds/pingback_title.html
{% load i18n %}
{{ obj.name }} {% trans "on" %} {{ obj.submit_date|date:"DATETIME_FORMAT" }}

grupyto-blog/templates/feeds/trackback_description.html
{{ obj.comment }}

grupyto-blog/templates/feeds/trackback_title.html
{% load i18n %}
{{ obj.name }} {% trans "on" %} {{ obj.submit_date|date:"DATETIME_FORMAT" }}

grupyto-blog/templates/pages/about.html
{% extends "base.html" %}

grupyto-blog/templates/pages/home.html
{% extends "base.html" %}

grupyto-blog/templates/users/user_detail.html
{% extends "base.html" %}
{% load avatar_tags %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->     
<div class="row">

  <div class="col-sm-12 ">
    <a class="btn btn-primary" href="{% url 'users:update' %}">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}">E-Mail</a>
    <a class="btn btn-info" href="{% url 'avatar_change' %}">Avatar</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

grupyto-blog/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}User: {{ user.username }}{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1>{% block header %}User: {{ user.username }}{% endblock %}</h1>
            <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="control-group">
                  <div class="controls">
                    <button type="submit" class="btn">Update</button>
                  </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

grupyto-blog/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% load avatar_tags %}

{% block title %}Members{% endblock %}

{% block content %}

<div class="container">
    
  <div class="row">
    <div class="col-xs-12">
      <h2>Users</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="list-group">
          {% for user in user_list %}
            <a href="{% url 'users:detail' user.username %}" class="list-group-item">
              <h4 class="list-group-item-heading">{% avatar user %} {{ user.username }}</h4>
              <p class="list-group-item-text">{{ maker.tagline }}</p>
            </a>
          {% endfor %}
        
      </div>
    </div>
  </div>

</div>

{% endblock content %}

grupyto-blog/templates/zinnia/author_list.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Author list" %}{% endblock meta-description %}

{% block title %}{% trans "Authors" %}{% endblock title %}

{% block body-class %}author-list{% endblock body-class %}

{% block content %}
<h2>{% trans "Author list" %}</h2>

<ul>
  {% for object in object_list %}
  <li class="vcard">
    <a href="{{ object.get_absolute_url }}"
       title="{% blocktrans with author=object %}Show all {{ author }}'s entries{% endblocktrans %}"
       class="fn url{% if not author.get_full_name %} nickname{% endif %}">{{ object }}</a>
    {% blocktrans count entry_count=object.count_entries_published %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
  </li>
  {% empty %}
  <li>
    {% trans "No authors yet." %}
  </li>
  {% endfor %}
</ul>
{% endblock content %}

grupyto-blog/templates/zinnia/category_list.html
{% extends "zinnia/base.html" %}
{% load i18n mptt_tags %}

{% block meta-description %}{% trans "Category list" %}{% endblock meta-description %}

{% block title %}{% trans "Categories" %}{% endblock title %}

{% block body-class %}category-list{% endblock body-class %}

{% block content %}
<h2>{% trans "Category list" %}</h2>

<ul class="category-root">
  {% recursetree object_list %}
  <li>
    <a href="{{ node.get_absolute_url }}" title="{% blocktrans with category=node %}Show all entries in {{ category }}{% endblocktrans %}">{{ node }}</a>
    {% blocktrans count entry_count=node.entries_published.count %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
    {% if node.description %}<p>{{ node.description|striptags|safe }}</p>{% endif %}
    {% if not node.is_leaf_node %}
    <ul class="category-children category-{{ node.slug }}">
      {{ children }}
    </ul>
    {% endif %}
  </li>
  {% endrecursetree %}
  {% if not object_list %}
  <li>
    {% trans "No categories yet." %}
  </li>
  {% endif %}
</ul>
{% endblock content %}

grupyto-blog/templates/zinnia/entry_archive.html
{% extends "zinnia/entry_list.html" %}
{% load i18n zinnia_tags %}

{% block meta-description %}{% trans "Latest entries" %}{% endblock meta-description %}

{% block title %}{% trans "Latest entries" %}{% endblock title %}

{% block body-class %}{{ block.super }} archive index {% now "\y\e\a\r-Y \m\o\n\t\h-m \w\e\ek-W \d\a\y-d" %}{% endblock body-class %}

{% block slider %}
{% get_featured_entries template="zinnia/tags/slider_entries.html" %}
{% endblock slider %}

{% block content-related %}
{% if date_list %}
<h2>{% trans "Yearly archives" %}</h2>
<ul>
  {% for date in date_list %}
  <li>
    <a href="{% url 'zinnia_entry_archive_year' date|date:"Y" %}" rel="archives">{{ date|date:"Y" }}</a>
  </li>
  {% endfor %}
</ul>
{% endif %}
{% endblock content-related %}

grupyto-blog/templates/zinnia/entry_detail.html
{% extends "zinnia/entry_detail_base.html" %}

grupyto-blog/templates/zinnia/entry_list.html
{% extends "zinnia/base.html" %}
{% load i18n zinnia_tags %}

{% block meta-description %}{% trans "Latest entries for" %} {% if category %}{% trans "the category" %} {{ category }}{% if category.description %}: {{ category.description|striptags|safe }}{% endif %}{% endif %}{% if tag %}{% trans "the tag" %} {{ tag }}{% endif %}{% if author %}{% trans "the author" %} {{ author }}{% endif %}{% endblock meta-description %}

{% block meta-description-page %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} {% trans "page" %} {{ page_obj.number }}{% endifnotequal %}{% endif %}{% endblock meta-description-page %}

{% block link %}
  {{ block.super }}
  {% if category %}
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed" %} {{ category }}" href="{% url 'zinnia_category_feed' category.tree_path %}" />
  {% endif %}
  {% if tag %}
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed" %} {{ tag }}" href="{% url 'zinnia_tag_feed' tag.name %}" />
  {% endif %}
  {% if author %}
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed" %} {{ author }}" href="{% url 'zinnia_author_feed' author.username %}" />
  {% endif %}
{% endblock link %}

{% block title %}{% if category %}{% trans "Category" %} {{ category }}{% endif %}{% if tag %}{% trans "Tag" %} {{ tag }}{% endif %}{% if author %}{% trans "Author" %} {{ author }}{% endif %}{% endblock title %}

{% block title-page %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} - {% trans "Page" %} {{ page_obj.number }}{% endifnotequal %}{% endif %}{% endblock title-page %}

{% block body-class %}entry-list{% if page_obj %} paginated page-{{ page_obj.number }}{% endif %}{% if category %} category category-{{ category.slug }}{% endif %}{% if tag %} tag tag-{{ tag|slugify }}{% endif %}{% if author %} author author-{{ author|slugify }}{% endif %}{% endblock body-class %}

{% block content %}

{% block content-title %}
{% if category %}
<h1>{% blocktrans %}Category archives: {{ category }}{% endblocktrans %}</h1>
{% if category.description %}
<p>{{ category.description|striptags|safe }}</p>
{% endif %}
{% endif %}

{% if tag %}
<h1>{% blocktrans %}Tag archives: {{ tag }}{% endblocktrans %}</h1>
{% endif %}

{% if author %}
<h1>{% blocktrans %}Author archives: {{ author }}{% endblocktrans %}</h1>
{% endif %}
{% endblock content-title %}

{% block content-loop %}
{% for object in object_list %}
  {% include object.content_template with object_content=object.html_preview continue_reading=1 %}
{% empty %}
  <p class="info">
    <a href="{% url 'admin:zinnia_entry_add' %}">{% trans "No entries yet." %}</a>
  </p>
{% endfor %}
{% endblock content-loop %}

{% block content-pagination %}
{% if is_paginated %}
  {% zinnia_pagination page_obj %}
{% endif %}
{% endblock content-pagination %}

{% block content-related %}
{% endblock content-related %}

{% endblock content %}

{% block admin-tools %}
  {% if category and perms.zinnia.change_category %}
  <li>
    <a href="{% url 'admin:zinnia_category_change' category.pk %}" title="{% trans "Edit the category" %}">
      {% trans "Edit the category" %}
    </a>
  </li>
  {% endif %}
  {% if tag and perms.tagging.change_tag %}
  <li>
    <a href="{% url 'admin:tagging_tag_change' tag.pk %}" title="{% trans "Edit the tag" %}">
      {% trans "Edit the tag" %}
    </a>
  </li>
  {% endif %}
  {% if author and perms.auth.change_user %}
  <li>
    <a href="{% url 'admin:auth_user_change' author.pk %}" title="{% trans "Edit the author" %}">
      {% trans "Edit the author" %}
    </a>
  </li>
  {% endif %}
{% endblock admin-tools %}